version: '3.7'

services:
  web:
    build: .
    command: >
      bash -c "
            python manage.py migrate --noinput &&
            python manage.py runserver 127.0.0.1:8000 --noreload"
    volumes:
      - .:/usr/src/paymentCartManagement
    ports:
      - 8000:8000
