version: '3.7'

services:
  web:
    build: .
    command: python /usr/src/paymentCartManagement/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/paymentCartManagement
    ports:
      - 8000:8000
