# Generated by Django 4.1.4 on 2022-12-26 08:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcard',
            name='cart_number',
            field=models.BigIntegerField(blank=True, default=4521270943744103, null=True, verbose_name='Номер карты'),
        ),
        migrations.AlterField(
            model_name='paymentcard',
            name='end_date_card_activity',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 6, 18, 8, 40, 25, 46330), null=True, verbose_name='дата окончания активности карты'),
        ),
    ]
