# Generated by Django 4.1.4 on 2022-12-26 09:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0003_alter_paymentcard_cart_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentcard',
            options={'ordering': ['-created_at'], 'verbose_name': 'Платежная карта', 'verbose_name_plural': 'Платежные карты'},
        ),
        migrations.AlterModelOptions(
            name='purchases',
            options={'ordering': ['-purchase_date'], 'verbose_name': 'Покупка', 'verbose_name_plural': 'Покупки'},
        ),
        migrations.AlterField(
            model_name='paymentcard',
            name='cart_number',
            field=models.BigIntegerField(blank=True, default=4228374860372876, null=True, verbose_name='Номер карты'),
        ),
        migrations.AlterField(
            model_name='paymentcard',
            name='end_date_card_activity',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 6, 18, 15, 57, 8, 135946), null=True, verbose_name='дата окончания активности карты'),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='cart_numbers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_numbers', to='source.paymentcard', verbose_name='Номер карты'),
        ),
    ]
