# Generated by Django 4.1.4 on 2022-12-26 11:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0004_alter_paymentcard_options_alter_purchases_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcard',
            name='cart_number',
            field=models.BigIntegerField(blank=True, default=4132073282931971, null=True, verbose_name='Номер карты'),
        ),
        migrations.AlterField(
            model_name='paymentcard',
            name='end_date_card_activity',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 6, 18, 17, 2, 8, 945048), null=True, verbose_name='дата окончания активности карты'),
        ),
    ]
