# Generated by Django 4.1.4 on 2022-12-26 11:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0005_alter_paymentcard_cart_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcard',
            name='cart_number',
            field=models.BigIntegerField(blank=True, default=4285397979267265, null=True, verbose_name='Номер карты'),
        ),
        migrations.AlterField(
            model_name='paymentcard',
            name='end_date_card_activity',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 6, 18, 17, 4, 39, 756540), null=True, verbose_name='дата окончания активности карты'),
        ),
    ]
